name: Terraform CI/CD

on:
  push:
    branches:
      - dev
      - master
    paths:
      - 'iac/**'  # Trigger only on changes in iac/ and its subdirectories

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: ${{ github.ref_name == 'dev' && 'cloud-nonprod-us-east-1' || 'cloud-prod-us-east-1' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: iac

      - name: Select Terraform Workspace
        run: terraform workspace select $TF_WORKSPACE
        working-directory: iac

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: iac

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: iac/tfplan

  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment: deployment
    env:
      TF_WORKSPACE: ${{ github.ref_name == 'dev' && 'cloud-nonprod-us-east-1' || 'cloud-prod-us-east-1' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: iac

      - name: Select Terraform Workspace
        run: terraform workspace select $TF_WORKSPACE
        working-directory: iac

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: iac/

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: iac